'use strict';
const PASS_SCORE = 40;
const $ = id => document.getElementById(id);
let questions, answers, current, finished;
function shuffle(list) { const a=[...list]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a; }
function makeAttempt(){return QUESTIONS.map(q=>{const order=shuffle([0,1,2,3]);return {...q,options:order.map(i=>q.options[i]),correct:order.indexOf(q.correct)};});}
function grade(qs, as){const correct=qs.reduce((n,q,i)=>n+(as[i]===q.correct?1:0),0);return {correct,percent:Math.round(correct/qs.length*100),passed:correct>=PASS_SCORE};}
function start(){questions=makeAttempt();answers=Array(questions.length).fill(null);current=0;finished=false;$('quiz').hidden=false;$('results').hidden=true;$('results').replaceChildren();$('status').textContent='';render();}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function updateOverview(){const n=answers.filter(a=>a!==null).length;$('count').textContent=`${n} / 50`;$('progress').value=n;$('grid').replaceChildren();questions.forEach((q,i)=>{const b=el('button',String(i+1));b.type='button';b.className=[answers[i]!==null?'answered':'',i===current?'current':''].join(' ');b.setAttribute('aria-label',`Pytanie ${i+1}, ${answers[i]!==null?'odpowiedziane':'bez odpowiedzi'}`);if(i===current)b.setAttribute('aria-current','step');b.onclick=()=>go(i);$('grid').append(b);});}
function render(){const q=questions[current];$('category').textContent=q.category;$('counter').textContent=`${current+1} / 50`;$('question').textContent=q.question;$('options').replaceChildren();q.options.forEach((text,i)=>{const label=el('label',undefined,'option'),input=el('input');input.type='radio';input.name='answer';input.value=i;input.checked=answers[current]===i;input.onchange=()=>{answers[current]=i;$('status').textContent='';updateOverview();};label.append(input,el('span','ABCD'[i],'option-letter'),el('span',text,'option-text'));$('options').append(label);});$('prev').disabled=current===0;$('next').textContent=current===49?'Sprawdź wynik':'Następne pytanie →';updateOverview();}
function focusQuestion(){const title=$('question');title.setAttribute('tabindex','-1');title.focus({preventScroll:true});title.scrollIntoView({block:'nearest',behavior:'auto'});}
function go(i){if(finished)return;current=i;render();focusQuestion();}
function finish(){if(finished)return;const missing=answers.findIndex(a=>a===null);if(missing!==-1){go(missing);$('status').textContent=`Odpowiedz na wszystkie pytania. Pozostało: ${answers.filter(a=>a===null).length}. Otwarto pierwsze pominięte pytanie (${missing+1}).`;return;}finished=true;const result=grade(questions,answers);$('quiz').hidden=true;const out=$('results');out.hidden=false;out.replaceChildren();const card=el('div',undefined,'result-card'),score=el('div',`${result.percent}%`,'score');score.append(el('span',`${result.correct} / 50 poprawnych odpowiedzi`));const intro=el('div');const h=el('h2',result.passed?'Quiz zaliczony':'Próg zaliczenia nieosiągnięty');h.tabIndex=-1;intro.append(h,el('p',result.passed?'Osiągnięto wymagane minimum 80%.':`Do zaliczenia brakuje ${PASS_SCORE-result.correct} poprawnych odpowiedzi. Próg: 40 z 50 (80%).`),el('p','Sprawdź poniżej odpowiedzi i wróć do wskazanych materiałów.'));card.append(score,intro);out.append(card);const actions=el('div',undefined,'result-actions'),again=el('button','Rozwiąż ponownie','primary');again.type='button';again.onclick=()=>{start();focusQuestion();};actions.append(el('h2','Omówienie odpowiedzi'),again);out.append(actions);questions.forEach((q,i)=>{const ok=answers[i]===q.correct,a=el('article',undefined,`review${ok?'':' wrong'}`);a.append(el('div',`${i+1} / 50 · ${ok?'Poprawna odpowiedź':'Błędna odpowiedź'} · ${q.category}`,'tag'),el('h3',q.question),el('p',`Twoja odpowiedź: ${'ABCD'[answers[i]]}. ${q.options[answers[i]]}`));if(!ok)a.append(el('p',`Prawidłowa odpowiedź: ${'ABCD'[q.correct]}. ${q.options[q.correct]}`));a.append(el('p',q.explanation));const details=el('details'),list=el('ol');list.type='A';q.options.forEach(o=>list.append(el('li',o)));details.append(el('summary','Wszystkie opcje'),list);a.append(details,el('p',`Źródło: ${q.source}`,'source'));out.append(a);});h.focus({preventScroll:true});out.scrollIntoView({block:'start'});}
$('prev').onclick=()=>go(current-1);$('next').onclick=()=>current===49?finish():go(current+1);$('finish').onclick=finish;$('question-form').onsubmit=e=>e.preventDefault();start();
